python:
  interpeter:
      path: '.\venv\Scripts\python.exe'  # TODO change when go to production!
logger:
  name: vmsm.log
gui:
  app:
    width: 850
    height: 600
  popup:
    width: 780
    height: 200
  export:
    width: 400
    height: 400
    pdf:
      name: report.pdf
  video_loader:
    folder:
      path: 'C:\Users\batel\Desktop\Projects\FinalProject\Tests'  # TODO change to C folder.
video_paths:
  mp4_video: 'results\\origin.mp4'
  temp_object: 'results\\temp_object.mp4'
  left_object: 'results\\left_object.mp4'
  left_object2: 'results\\left_object2.mp4'
  right_object: 'results\\right_object.mp4'
  right_object2: 'results\\right_object2.mp4'
  mid_res: 'results\\middle_result.mp4'
  res: 'results\\'
  cutted: 'results\\cutted.mp4'
video_processing:
  allow:
    following_frames_treshold: 100
