GUI:
  APP:
    WIDTH: 850
    HEIGHT: 600

VIDEO_PATHS:
  first_object: results\\1st_result.mp4
  first_object2: results\\1st_result2.mp4
  second_object: results\\2nd_result.mp4
  second_object2: results\\2nd_result2.mp4
  mid_res: results\\middle_result.mp4
  res: results\\

VIDEO_PROCESSING:
  ALLOW:
    FOLLOWING_FRAMES_THRESHOLD: 100
